# Generated by Django 6.1.1 on 2026-09-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=255)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ataque1', models.CharField(max_length=50)),
                ('ataque2', models.CharField(max_length=50)),
            ],
        ),
    ]
